name: Git CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/sync4_rsa"
          cd ~
          test -d zorgportal-wp || {
            git clone git@github.com:elhardoum/zorgportal-wp.git zorgportal-wp
          }
          cd ~/zorgportal-wp
          git pull origin master
          # install any composer deps / generate autoload
          cd src
          docker run --rm --volume $(pwd):/app prooph/composer:7.2 install --ignore-platform-reqs
